=== tanchinsheng/java/sonar-training/tpms/tpms-web/WebContent/cfg/local_cfg/plants.dtd
<!-- SYNTAX FOR DATABASES ACCESS DEFINITION -->

<!ELEMENT SYSTEM (PLANTS*)>

<!ELEMENT PLANTS (MODEL_ID,PL_NAME,DBS_TYPE,USERNAME,PASSWORD,CONN_STR?)>

<!ELEMENT MODEL_ID (#PCDATA)>
<!ELEMENT PL_NAME  (#PCDATA)>
<!ELEMENT DBS_TYPE (#PCDATA)>
<!ELEMENT USERNAME (#PCDATA)>
<!ELEMENT PASSWORD (#PCDATA)>
<!ELEMENT CONN_STR (#PCDATA)>

=== tanchinsheng/java/sonar-training/tpms/tpms-web/WebContent/cfg/local_cfg/plants.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by txt (txt) -->
<!DOCTYPE SYSTEM SYSTEM 'plants.dtd'>
<SYSTEM>
    <PLANTS>
        <MODEL_ID>MAIN</MODEL_ID>
        <PL_NAME>MAIN</PL_NAME>
        <DBS_TYPE>ORACLE</DBS_TYPE>
        <USERNAME>TPMS</USERNAME>
        <PASSWORD>VjJ0V2IxRXlVa2hVYWs1UlZrUkJPUT09</PASSWORD>
        <CONN_STR>172.30.201.7:1521:DAIT</CONN_STR>
    </PLANTS>
</SYSTEM>
