=== tanchinsheng/java/sonar-training/tpms/tpms-web/WebContent/cfg/db_int/joins.dtd
<!-- SYNTAX FOR JOINS DEFINITIONS -->

<!ELEMENT JOINS (JOIN*)>

<!ELEMENT JOIN (JOIN_ID,DBTABLEA,DBTABLEB,JOINFLDA,JOINFLDB)>

<!ELEMENT JOIN_ID (#PCDATA)>
	<!ATTLIST JOIN_ID type (D|N|C) #IMPLIED>
<!ELEMENT DBTABLEA (#PCDATA)>
	<!ATTLIST DBTABLEA type (D|N|C) #IMPLIED>
<!ELEMENT DBTABLEB (#PCDATA)>
	<!ATTLIST DBTABLEB type (D|N|C) #IMPLIED>
<!ELEMENT JOINFLDA (#PCDATA)>
	<!ATTLIST JOINFLDA type (D|N|C) #IMPLIED>
<!ELEMENT JOINFLDB (#PCDATA)>
	<!ATTLIST JOINFLDB type (D|N|C) #IMPLIED>

=== tanchinsheng/java/sonar-training/tpms/tpms-web/WebContent/cfg/db_int/MAIN/joins.xml
<?xml version="1.0"?>
<!-- edited with XML Spy v4.3 U (http://www.xmlspy.com) by Daniele Colecchia (TXT e-solutions s.p.a.) -->
<!DOCTYPE JOINS SYSTEM "../joins.dtd">
<JOINS>
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_HISTORY</DBTABLEB>
        <JOINFLDA>JOBNAME</JOINFLDA>
        <JOINFLDB>JOBNAME</JOINFLDB>
    </JOIN>
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_HISTORY</DBTABLEB>
        <JOINFLDA>JOB_RELEASE</JOINFLDA>
        <JOINFLDB>JOB_RELEASE</JOINFLDB>
    </JOIN>
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_HISTORY</DBTABLEB>
        <JOINFLDA>JOB_REVISION</JOINFLDA>
        <JOINFLDB>JOB_REVISION</JOINFLDB>
    </JOIN>
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_HISTORY</DBTABLEB>
        <JOINFLDA>TPMS_VER</JOINFLDA>
        <JOINFLDB>TPMS_VER</JOINFLDB>
    </JOIN>
    <!--tp comments-->
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_COMMENTS</DBTABLEB>
        <JOINFLDA>JOBNAME</JOINFLDA>
        <JOINFLDB>JOBNAME</JOINFLDB>
    </JOIN>
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_COMMENTS</DBTABLEB>
        <JOINFLDA>JOB_RELEASE</JOINFLDA>
        <JOINFLDB>JOB_RELEASE</JOINFLDB>
    </JOIN>
    <JOIN>
        <JOIN_ID>1</JOIN_ID>
        <DBTABLEA>TP_PLANT</DBTABLEA>
        <DBTABLEB>TP_COMMENTS</DBTABLEB>
        <JOINFLDA>JOB_REVISION</JOINFLDA>
        <JOINFLDB>JOB_REVISION</JOINFLDB>
    </JOIN>
</JOINS>
